### ISSUE TITLE
Make: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by eleius** [tgragnato/magnetico#165]
When running make, right after the TestFlush test, it stops with the following error.
I'm not experienced in go, what should I do to build it?

```
2024/03/13 09:40:24 Updating database schema from 0 to 1... (this might take a while)
2024/03/13 09:40:24 Updating database schema from 1 to 2... (this might take a while)
2024/03/13 09:40:24 Updating database schema from 2 to 3... (this might take a while)
=== RUN   TestTorrentMetadata_MarshalJSON
--- PASS: TestTorrentMetadata_MarshalJSON (0.00s)
=== RUN   TestNewStatistics
--- PASS: TestNewStatistics (0.00s)
=== RUN   TestParseISO8601
=== PAUSE TestParseISO8601
=== RUN   TestDaysOfMonth
--- PASS: TestDaysOfMonth (0.00s)
=== RUN   TestIsLeap
--- PASS: TestIsLeap (0.00s)
=== RUN   TestPostgresDatabase_ExecuteTemplate
--- PASS: TestPostgresDatabase_ExecuteTemplate (0.00s)
=== RUN   TestPostgresDatabase_OrderOn
--- PASS: TestPostgresDatabase_OrderOn (0.00s)
=== RUN   Test_sqlite3Database_DoesTorrentExist
=== PAUSE Test_sqlite3Database_DoesTorrentExist
=== RUN   Test_sqlite3Database_GetNumberOfTorrents
=== PAUSE Test_sqlite3Database_GetNumberOfTorrents
=== RUN   Test_sqlite3Database_AddNewTorrent
=== PAUSE Test_sqlite3Database_AddNewTorrent
=== RUN   Test_sqlite3Database_QueryTorrents
=== PAUSE Test_sqlite3Database_QueryTorrents
=== RUN   Test_sqlite3Database_GetTorrent
=== PAUSE Test_sqlite3Database_GetTorrent
=== RUN   Test_sqlite3Database_GetFiles
=== PAUSE Test_sqlite3Database_GetFiles
=== RUN   Test_sqlite3Database_GetStatistics
=== PAUSE Test_sqlite3Database_GetStatistics
=== CONT  Test_sqlite3Database_DoesTorrentExist
=== CONT  Test_sqlite3Database_QueryTorrents
=== RUN   Test_sqlite3Database_QueryTorrents/Test_Relevance
=== RUN   Test_sqlite3Database_DoesTorrentExist/Test_Empty
--- FAIL: Test_sqlite3Database_QueryTorrents (0.00s)
    --- FAIL: Test_sqlite3Database_QueryTorrents/Test_Relevance (0.00s)
=== CONT  Test_sqlite3Database_AddNewTorrent
=== RUN   Test_sqlite3Database_AddNewTorrent/Test_Nil
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0xc51f6b]

goroutine 3 [running]:
testing.tRunner.func1.2({0xddf080, 0x1382280})
	/usr/lib/go/src/testing/testing.go:1631 +0x3f7
testing.tRunner.func1()
	/usr/lib/go/src/testing/testing.go:1634 +0x6b6
panic({0xddf080?, 0x1382280?})
	/usr/lib/go/src/runtime/panic.go:770 +0x132
github.com/tgragnato/magnetico/persistence.Test_sqlite3Database_QueryTorrents.func1(0xc0000b2000)
	/opt/magnetico/persistence/sqlite3_test.go:174 +0xab
testing.tRunner(0xc0000b2000, 0xc0000ac000)
	/usr/lib/go/src/testing/testing.go:1689 +0x21f
created by testing.(*T).Run in goroutine 34
	/usr/lib/go/src/testing/testing.go:1742 +0x826
FAIL	github.com/tgragnato/magnetico/persistence	0.046s
FAIL
make: *** [Makefile:15: test] Error 1

```

**Comment by tgragnato** [comment]
Hello @eleius,
Thank you for reporting this issue!

I've just pushed a fix, a compilation flag was missing in the makefile. You can proceed with the installation of magnetico using `make` as you were doing before; it should work smoothly now.

You will find the two binaries here: `~/go/bin/magneticod` , `~/go/bin/magneticow`.

As you may have noticed, I'm trying to reintroduce support for SQLite. Any assistance or feedback is greatly appreciated, so please feel free to share your insights and suggestions.
